import question1 from "./image/EXXXX.png";
import question2 from "./image/lusamut.png";
import question3 from "./image/Gizhem.png";
import question4 from "./image/ag@.png";
import question5 from "./image/knik.png";
import question6 from "./image/hambal.png"
import question7 from "./image/paka.png";
import question8 from "./image/raf.png";
import question9 from "./image/nker.png";
import question10 from "./image/xosq.png"
import question11 from "./image/utelu.png";
import question12 from "./image/urax.png";
import question13 from "./image/furer.png"
import question14 from "./image/Duq.png";
import question15 from "./image/gisher.png";
import question16 from "./image/nver.png"

export const questions = [
    {
        questionImg: question1,
        question: 'Ex sharjenq...',
        answer1: 'Ansharj@',
        answer2: 'Sharjakan@',
        answer3: 'Sexan@',
        answer4: 'Ator@',
        correct: 1,
        fifty: [1,4],
        audience: [71,19,6,4],
    },
    {
        questionImg: question2,
        question: 'Lusamut@...',
        answer1: 'Sarqim',
        answer2: 'Berim',
        answer3: 'Drim',
        answer4: 'Dreci',
        correct: 3,
        fifty: [3,4],
        audience: [5,10,45,40],
    },
    {
        questionImg: question3,
        question: 'Es karoxa gizhem bayc...',
        answer1: 'Xeloq chem',
        answer2: 'Du hastat xeloq ches',
        answer3: 'Chem Gzhvel',
        answer4: 'Tupoy chem',
        correct: 4,
        fifty: [2,4],
        audience: [5,20,15,60],
    },
    {
        questionImg: question4,
        question: 'Hagop...',
        answer1: 'Ak@',
        answer2: 'laves?',
        answer3: 'erexeq@ voncen?',
        answer4: 'inch arir?',
        correct: 1,
        fifty: [1,4],
        audience: [80,10,5,5],
    },
    {
        questionImg: question5,
        question: 'Shnik jan, ee...',
        answer1: 'Canot jan',
        answer2: 'Knik jan',
        answer3: 'Katvik jan',
        answer4: 'Gna gorcid',
        correct: 2,
        fifty: [2,3],
        audience: [5,50,40,5],
    },
    {
        questionImg: question6,
        question: 'Brnel a...',
        answer1: 'talis xelar',
        answer2: 'uzum ta',
        answer3: 'tali hambal@',
        answer4: 'uzum',
        correct: 3,
        fifty: [1,3],
        audience: [40,10,45,5],
    },
    {
        questionImg: question7,
        question: 'Kakoy privet takoy...',
        answer1: 'privet',
        answer2: 'paka',
        answer3: 'idi naxoroq mtaci',
        answer4: 'atvet',
        correct: 2,
        fifty: [2,4],
        audience: [10,50,5,35],
    },
    {
        questionImg: question8,
        question: 'Inchu es hayhoyum gitutyan as gyut@ vori annune...',
        answer1: 'Israel',
        answer2: 'Zhiguli',
        answer3: 'meqena',
        answer4: 'rafael',
        correct: 4,
        fifty: [2,4],
        audience: [5,10,40,45],
    },
    {
        questionImg: question9,
        question: 'Nker naxagah, vonc qcum brnumem',
        answer1: 'es Sahaki glux@ pti jardem',
        answer2: 'es Sahakin mormsh pti anem',
        answer3: 'pti zangem Dogin',
        answer4: 'petqa satkacnem',
        correct: 1,
        fifty: [1,4],
        audience: [60,10,5,25],
    },
    {
        questionImg: question10,
        question: 'Lsi quro jan, es uzumes erexus xosq@',
        answer1: 'ttvi vret',
        answer2: 'sax kyanq asnavani chlini',
        answer3: 'mna vzit',
        answer4: 'himq chlini',
        correct: 2,
        fifty: [2,4],
        audience: [10,50,5,35],
    },
    {
        questionImg: question11,
        question: 'Chax hel...',
        answer1: 'eli hac es utelu',
        answer2: 'tun en gnum',
        answer3: 'eli eli hac es utelu',
        answer4: 'mi qni axchi ay hambal',
        correct: 1,
        fifty: [1,3],
        audience: [70,10,5,15],
    },
    {
        questionImg: question12,
        question: 'Misht senc...',
        answer1: 'jan aseq jan lseq',
        answer2: 'exeq',
        answer3: 'aritnerov irar handipenq',
        answer4: 'ancni mer aroryan',
        correct: 3,
        fifty: [2,3],
        audience: [10,30,55,5],
    },
    {
        questionImg: question13,
        question: 'Et sev ikrayov fur@ darnuma...',
        answer1: 'msov fur',
        answer2: 'esim inch',
        answer3: 'garoxov fur',
        answer4: 'lav balik',
        correct: 3,
        fifty: [1,3],
        audience: [30,10,55,5],
    },
    {
        questionImg: question14,
        question: 'Duq mrganushi...',
        answer1: 'garlaxner',
        answer2: 'mormshnerneq',
        answer3: 'lav apernerm eq',
        answer4: 'manyaknerneq',
        correct: 1,
        fifty: [1,3],
        audience: [50,10,35,5],
    },
    {
        questionImg: question15,
        question: 'Imijayloc gisherva ntacqum es... ',
        answer1: 'taks ei arel',
        answer2: 'ereq angam durs ei ekel',
        answer3: 'erku angam durs ei ekel',
        answer4: 'klorakic durs ei ekel',
        correct: 3,
        fifty: [2,3],
        audience: [10,25,50,15],
    },
    {
        questionImg: question16,
        question: 'Nnenc nver piti anenq vor...',
        answer1: 'chmorana',
        answer2: 'sax kyanq hishi',
        answer3: 'chposhmani',
        answer4: 'urxna',
        correct: 2,
        fifty: [1,2],
        audience: [60,25,10,5],
    }
]